-- Migration to remove unused columns from candidates table and keep only the specified ones.

ALTER TABLE public.candidates
  DROP COLUMN IF EXISTS status,
  DROP COLUMN IF EXISTS workflow_status,
  DROP COLUMN IF EXISTS current_step,
  DROP COLUMN IF EXISTS background_check_initiated_at,
  DROP COLUMN IF EXISTS pre_joining_introduced_at,
  DROP COLUMN IF EXISTS buddy_assigned_at,
  DROP COLUMN IF EXISTS send_goodies_at,
  DROP COLUMN IF EXISTS send_laptop_at,
  DROP COLUMN IF EXISTS background_check_status,
  DROP COLUMN IF EXISTS background_check_comments,
  DROP COLUMN IF EXISTS background_check_completed_at,
  DROP COLUMN IF EXISTS background_check_completed_by,
  DROP COLUMN IF EXISTS pre_joining_status,
  DROP COLUMN IF EXISTS pre_joining_comments,
  DROP COLUMN IF EXISTS pre_joining_completed_at,
  DROP COLUMN IF EXISTS pre_joining_completed_by,
  DROP COLUMN IF EXISTS buddy_assignment_status,
  DROP COLUMN IF EXISTS buddy_assignment_comments,
  DROP COLUMN IF EXISTS buddy_assignment_completed_at,
  DROP COLUMN IF EXISTS buddy_assignment_completed_by,
  DROP COLUMN IF EXISTS goodies_status,
  DROP COLUMN IF EXISTS goodies_comments,
  DROP COLUMN IF EXISTS goodies_completed_at,
  DROP COLUMN IF EXISTS goodies_completed_by,
  DROP COLUMN IF EXISTS laptop_status,
  DROP COLUMN IF EXISTS laptop_comments,
  DROP COLUMN IF EXISTS laptop_completed_at,
  DROP COLUMN IF EXISTS laptop_completed_by;