"""migrate_rest_to_uuid

Revision ID: 3d02f2033375
Revises: 7a19939216d5
Create Date: 2026-03-21 10:39:57.678043

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d02f2033375'
down_revision: Union[str, None] = '42073ca3c7ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('oauth_states',
    sa.Column('state', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('state')
    )
    op.create_index('idx_oauth_states_expires_at', 'oauth_states', ['expires_at'], unique=False)
    op.create_table('one_time_codes',
    sa.Column('code', sa.String(length=255), nullable=False),
    sa.Column('employee_id', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_index('idx_one_time_codes_employee_id', 'one_time_codes', ['employee_id'], unique=False)
    op.create_index('idx_one_time_codes_expires_at', 'one_time_codes', ['expires_at'], unique=False)
    op.create_table('entra_group_role_mappings',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('entra_group_id', sa.String(length=255), nullable=False),
    sa.Column('entra_group_name', sa.String(length=255), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entra_group_id')
    )
    op.create_index('idx_entra_group_mappings_deleted_at', 'entra_group_role_mappings', ['deleted_at'], unique=False)
    op.create_index('idx_entra_group_mappings_role_id', 'entra_group_role_mappings', ['role_id'], unique=False)
    op.alter_column('asset_categories', 'code',
               existing_type=sa.VARCHAR(length=5),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.add_column('employees', sa.Column('entra_oid', sa.String(length=255), nullable=True))
    op.create_index('idx_employees_entra_oid', 'employees', ['entra_oid'], unique=False)
    op.create_unique_constraint(None, 'employees', ['entra_oid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'employees', type_='unique')
    op.drop_index('idx_employees_entra_oid', table_name='employees')
    op.drop_column('employees', 'entra_oid')
    op.alter_column('asset_categories', 'code',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=5),
               existing_nullable=True)
    op.drop_index('idx_entra_group_mappings_role_id', table_name='entra_group_role_mappings')
    op.drop_index('idx_entra_group_mappings_deleted_at', table_name='entra_group_role_mappings')
    op.drop_table('entra_group_role_mappings')
    op.drop_index('idx_one_time_codes_expires_at', table_name='one_time_codes')
    op.drop_index('idx_one_time_codes_employee_id', table_name='one_time_codes')
    op.drop_table('one_time_codes')
    op.drop_index('idx_oauth_states_expires_at', table_name='oauth_states')
    op.drop_table('oauth_states')
    # ### end Alembic commands ###
