"""migrate_ids_to_uuid_all

Revision ID: 42073ca3c7ee
Revises: 6ac27259d060
Create Date: 2026-03-19 10:18:40.856461

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42073ca3c7ee'
down_revision: Union[str, None] = '6ac27259d060'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 1. Drop all foreign keys robustly
    op.execute("""
        DO $$ 
        DECLARE 
            r RECORD;
        BEGIN
            FOR r IN (SELECT constraint_name, table_name 
                      FROM information_schema.table_constraints 
                      WHERE constraint_type = 'FOREIGN KEY') 
            LOOP
                EXECUTE 'ALTER TABLE ' || quote_ident(r.table_name) || ' DROP CONSTRAINT ' || quote_ident(r.constraint_name);
            END LOOP;
        END $$;
    """)

    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('applications', 'id', server_default=sa.text('gen_random_uuid()'),
               existing_type=sa.VARCHAR(length=255),
               type_=sa.UUID(),
               existing_nullable=False, postgresql_using="CASE WHEN id ~ '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$' THEN id::uuid ELSE md5(id)::uuid END")
    op.alter_column('applications', 'candidate_id',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.UUID(),
               existing_nullable=True, postgresql_using="CASE WHEN candidate_id ~ '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$' THEN candidate_id::uuid ELSE md5(candidate_id)::uuid END")
    op.alter_column('applications', 'requisition_id',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.UUID(),
               existing_nullable=True, postgresql_using="CASE WHEN requisition_id ~ '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$' THEN requisition_id::uuid ELSE md5(requisition_id)::uuid END")
    op.alter_column('applications', 'owner_id',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.UUID(),
               existing_nullable=True, postgresql_using="CASE WHEN owner_id ~ '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$' THEN owner_id::uuid ELSE md5(owner_id)::uuid END")
    op.alter_column('approvals', 'id', server_default=sa.text('gen_random_uuid()'),
               existing_type=sa.VARCHAR(length=255),
               type_=sa.UUID(),
               existing_nullable=False, postgresql_using="CASE WHEN id ~ '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$' THEN id::uuid ELSE md5(id)::uuid END")
    op.alter_column('approvals', 'resource_id',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.UUID(),
               existing_nullable=False, postgresql_using="CASE WHEN resource_id ~ '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$' THEN resource_id::uuid ELSE md5(resource_id)::uuid END")
    op.alter_column('approvals', 'task_id',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.UUID(),
               existing_nullable=True, postgresql_using="CASE WHEN task_id ~ '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$' THEN task_id::uuid ELSE md5(task_id)::uuid END")
    op.alter_column('approvals', 'approver_group_id',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.UUID(),
               existing_nullable=True, postgresql_using="CASE WHEN approver_group_id ~ '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$' THEN approver_group_id::uuid ELSE md5(approver_group_id)::uuid END")
    op.alter_column('approvals', 'approver_user_id',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.UUID(),
               existing_nullable=True, postgresql_using="CASE WHEN approver_user_id ~ '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$' THEN approver_user_id::uuid ELSE md5(approver_user_id)::uuid END")
    op.alter_column('asset_assignment_history', 'id', server_default=sa.text('gen_random_uuid()'),
               existing_type=sa.VARCHAR(length=255),
               type_=sa.UUID(),
               existing_nullable=False, postgresql_using="CASE WHEN id ~ '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$' THEN id::uuid ELSE md5(id)::uuid END")
    op.alter_column('asset_assignment_history', 'assigned_to',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.UUID(),
               existing_nullable=True, postgresql_using="CASE WHEN assigned_to ~ '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$' THEN assigned_to::uuid ELSE md5(assigned_to)::uuid END")
    op.alter_column('asset_assignment_history', 'assigned_by',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.UUID(),
               existing_nullable=True, postgresql_using="CASE WHEN assigned_by ~ '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$' THEN assigned_by::uuid ELSE md5(assigned_by)::uuid END")
    op.alter_column('asset_attachments', 'id', server_default=sa.text('gen_random_uuid()'),
               existing_type=sa.VARCHAR(length=255),
               type_=sa.UUID(),
               existing_nullable=False, postgresql_using="CASE WHEN id ~ '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$' THEN id::uuid ELSE md5(id)::uuid END")
    op.alter_column('asset_attachments', 'uploaded_by',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.UUID(),
               existing_nullable=True, postgresql_using="CASE WHEN uploaded_by ~ '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$' THEN uploaded_by::uuid ELSE md5(uploaded_by)::uuid END")
    op.alter_column('asset_categories', 'id', server_default=sa.text('gen_random_uuid()'),
               existing_type=sa.VARCHAR(length=255),
               type_=sa.UUID(),
               existing_nullable=False, postgresql_using="CASE WHEN id ~ '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$' THEN id::uuid ELSE md5(id)::uuid END")
    op.drop_constraint(op.f('asset_categories_code_key'), 'asset_categories', type_='unique')
    op.drop_constraint(op.f('asset_categories_name_key'), 'asset_categories', type_='unique')
    op.create_index('idx_asset_categories_name', 'asset_categories', ['name'], unique=False)
    op.create_unique_constraint('uq_asset_categories_code', 'asset_categories', ['code'])
    op.alter_column('assets', 'category_id',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.UUID(),
               existing_nullable=True, postgresql_using="CASE WHEN category_id ~ '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$' THEN category_id::uuid ELSE md5(category_id)::uuid END")
    op.alter_column('assets', 'assigned_to',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.UUID(),
               existing_nullable=True, postgresql_using="CASE WHEN assigned_to ~ '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$' THEN assigned_to::uuid ELSE md5(assigned_to)::uuid END")
    op.alter_column('ats_candidates', 'id', server_default=sa.text('gen_random_uuid()'),
               existing_type=sa.VARCHAR(length=255),
               type_=sa.UUID(),
               existing_nullable=False, postgresql_using="CASE WHEN id ~ '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$' THEN id::uuid ELSE md5(id)::uuid END")
    op.alter_column('audit_events', 'id', server_default=sa.text('gen_random_uuid()'),
               existing_type=sa.VARCHAR(length=255),
               type_=sa.UUID(),
               existing_nullable=False, postgresql_using="CASE WHEN id ~ '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$' THEN id::uuid ELSE md5(id)::uuid END")
    op.alter_column('audit_events', 'actor_id',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.UUID(),
               existing_nullable=True, postgresql_using="CASE WHEN actor_id ~ '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$' THEN actor_id::uuid ELSE md5(actor_id)::uuid END")
    op.alter_column('candidate_activities', 'id', server_default=sa.text('gen_random_uuid()'),
               existing_type=sa.VARCHAR(length=255),
               type_=sa.UUID(),
               existing_nullable=False, postgresql_using="CASE WHEN id ~ '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$' THEN id::uuid ELSE md5(id)::uuid END")
    op.alter_column('candidate_activities', 'candidate_id',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.UUID(),
               existing_nullable=False, postgresql_using="CASE WHEN candidate_id ~ '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$' THEN candidate_id::uuid ELSE md5(candidate_id)::uuid END")
    op.alter_column('candidate_activities', 'actor_id',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.UUID(),
               existing_nullable=True, postgresql_using="CASE WHEN actor_id ~ '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$' THEN actor_id::uuid ELSE md5(actor_id)::uuid END")
    op.alter_column('config_dropdowns', 'id', server_default=sa.text('gen_random_uuid()'),
               existing_type=sa.VARCHAR(length=255),
               type_=sa.UUID(),
               existing_nullable=False, postgresql_using="CASE WHEN id ~ '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$' THEN id::uuid ELSE md5(id)::uuid END")
    op.alter_column('config_dropdowns', 'created_by',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.UUID(),
               existing_nullable=True, postgresql_using="CASE WHEN created_by ~ '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$' THEN created_by::uuid ELSE md5(created_by)::uuid END")
    op.alter_column('dashboard_tasks', 'id', server_default=sa.text('gen_random_uuid()'),
               existing_type=sa.VARCHAR(length=255),
               type_=sa.UUID(),
               existing_nullable=False, postgresql_using="CASE WHEN id ~ '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$' THEN id::uuid ELSE md5(id)::uuid END")
    op.alter_column('dashboard_tasks', 'source_record_id',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.UUID(),
               existing_nullable=False, postgresql_using="CASE WHEN source_record_id ~ '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$' THEN source_record_id::uuid ELSE md5(source_record_id)::uuid END")
    op.alter_column('dashboard_tasks', 'assigned_to_id',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.UUID(),
               existing_nullable=True, postgresql_using="CASE WHEN assigned_to_id ~ '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$' THEN assigned_to_id::uuid ELSE md5(assigned_to_id)::uuid END")
    op.alter_column('employee_attachments', 'id', server_default=sa.text('gen_random_uuid()'),
               existing_type=sa.VARCHAR(length=255),
               type_=sa.UUID(),
               existing_nullable=False, postgresql_using="CASE WHEN id ~ '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$' THEN id::uuid ELSE md5(id)::uuid END")
    op.alter_column('employee_attachments', 'employee_id',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.UUID(),
               existing_nullable=False, postgresql_using="CASE WHEN employee_id ~ '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$' THEN employee_id::uuid ELSE md5(employee_id)::uuid END")
    op.alter_column('employee_attachments', 'uploaded_by',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.UUID(),
               existing_nullable=True, postgresql_using="CASE WHEN uploaded_by ~ '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$' THEN uploaded_by::uuid ELSE md5(uploaded_by)::uuid END")
    op.alter_column('employee_certifications', 'id', server_default=sa.text('gen_random_uuid()'),
               existing_type=sa.VARCHAR(length=255),
               type_=sa.UUID(),
               existing_nullable=False, postgresql_using="CASE WHEN id ~ '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$' THEN id::uuid ELSE md5(id)::uuid END")
    op.alter_column('employee_certifications', 'employee_id',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.UUID(),
               existing_nullable=False, postgresql_using="CASE WHEN employee_id ~ '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$' THEN employee_id::uuid ELSE md5(employee_id)::uuid END")
    op.alter_column('employee_emergency_contacts', 'id', server_default=sa.text('gen_random_uuid()'),
               existing_type=sa.VARCHAR(length=255),
               type_=sa.UUID(),
               existing_nullable=False, postgresql_using="CASE WHEN id ~ '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$' THEN id::uuid ELSE md5(id)::uuid END")
    op.alter_column('employee_emergency_contacts', 'employee_id',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.UUID(),
               existing_nullable=False, postgresql_using="CASE WHEN employee_id ~ '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$' THEN employee_id::uuid ELSE md5(employee_id)::uuid END")
    op.alter_column('employee_project_history', 'id', server_default=sa.text('gen_random_uuid()'),
               existing_type=sa.VARCHAR(length=255),
               type_=sa.UUID(),
               existing_nullable=False, postgresql_using="CASE WHEN id ~ '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$' THEN id::uuid ELSE md5(id)::uuid END")
    op.alter_column('employee_project_history', 'employee_id',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.UUID(),
               existing_nullable=False, postgresql_using="CASE WHEN employee_id ~ '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$' THEN employee_id::uuid ELSE md5(employee_id)::uuid END")
    op.alter_column('employee_project_history', 'project_id',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.UUID(),
               existing_nullable=True, postgresql_using="CASE WHEN project_id ~ '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$' THEN project_id::uuid ELSE md5(project_id)::uuid END")
    op.alter_column('employee_project_history', 'created_by',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.UUID(),
               existing_nullable=True, postgresql_using="CASE WHEN created_by ~ '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$' THEN created_by::uuid ELSE md5(created_by)::uuid END")
    op.alter_column('employee_rates', 'id', server_default=sa.text('gen_random_uuid()'),
               existing_type=sa.VARCHAR(length=255),
               type_=sa.UUID(),
               existing_nullable=False, postgresql_using="CASE WHEN id ~ '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$' THEN id::uuid ELSE md5(id)::uuid END")
    op.alter_column('employee_rates', 'employee_id',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.UUID(),
               existing_nullable=False, postgresql_using="CASE WHEN employee_id ~ '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$' THEN employee_id::uuid ELSE md5(employee_id)::uuid END")
    op.alter_column('employee_skills', 'employee_id',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.UUID(),
               existing_nullable=False, postgresql_using="CASE WHEN employee_id ~ '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$' THEN employee_id::uuid ELSE md5(employee_id)::uuid END")
    op.alter_column('employee_skills', 'skill_id',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.UUID(),
               existing_nullable=False, postgresql_using="CASE WHEN skill_id ~ '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$' THEN skill_id::uuid ELSE md5(skill_id)::uuid END")
    op.alter_column('employees', 'id', server_default=sa.text('gen_random_uuid()'),
               existing_type=sa.VARCHAR(length=255),
               type_=sa.UUID(),
               existing_nullable=False, postgresql_using="CASE WHEN id ~ '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$' THEN id::uuid ELSE md5(id)::uuid END")
    op.alter_column('employees', 'manager_id',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.UUID(),
               existing_nullable=True, postgresql_using="CASE WHEN manager_id ~ '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$' THEN manager_id::uuid ELSE md5(manager_id)::uuid END")
    op.alter_column('group_members', 'id', server_default=sa.text('gen_random_uuid()'),
               existing_type=sa.VARCHAR(length=255),
               type_=sa.UUID(),
               existing_nullable=False, postgresql_using="CASE WHEN id ~ '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$' THEN id::uuid ELSE md5(id)::uuid END")
    op.alter_column('group_members', 'group_id',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.UUID(),
               existing_nullable=False, postgresql_using="CASE WHEN group_id ~ '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$' THEN group_id::uuid ELSE md5(group_id)::uuid END")
    op.alter_column('group_members', 'employee_id',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.UUID(),
               existing_nullable=False, postgresql_using="CASE WHEN employee_id ~ '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$' THEN employee_id::uuid ELSE md5(employee_id)::uuid END")
    op.alter_column('holidays', 'id', server_default=sa.text('gen_random_uuid()'),
               existing_type=sa.VARCHAR(length=255),
               type_=sa.UUID(),
               existing_nullable=False, postgresql_using="CASE WHEN id ~ '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$' THEN id::uuid ELSE md5(id)::uuid END")
    op.alter_column('intake_approvals', 'id', server_default=sa.text('gen_random_uuid()'),
               existing_type=sa.VARCHAR(length=255),
               type_=sa.UUID(),
               existing_nullable=False, postgresql_using="CASE WHEN id ~ '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$' THEN id::uuid ELSE md5(id)::uuid END")
    op.alter_column('intake_approvals', 'intake_id',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.UUID(),
               existing_nullable=False, postgresql_using="CASE WHEN intake_id ~ '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$' THEN intake_id::uuid ELSE md5(intake_id)::uuid END")
    op.alter_column('intake_approvals', 'approver_id',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.UUID(),
               existing_nullable=False, postgresql_using="CASE WHEN approver_id ~ '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$' THEN approver_id::uuid ELSE md5(approver_id)::uuid END")
    op.alter_column('intake_audit', 'id', server_default=sa.text('gen_random_uuid()'),
               existing_type=sa.VARCHAR(length=255),
               type_=sa.UUID(),
               existing_nullable=False, postgresql_using="CASE WHEN id ~ '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$' THEN id::uuid ELSE md5(id)::uuid END")
    op.alter_column('intake_audit', 'intake_id',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.UUID(),
               existing_nullable=False, postgresql_using="CASE WHEN intake_id ~ '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$' THEN intake_id::uuid ELSE md5(intake_id)::uuid END")
    op.alter_column('intake_audit', 'actor_id',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.UUID(),
               existing_nullable=True, postgresql_using="CASE WHEN actor_id ~ '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$' THEN actor_id::uuid ELSE md5(actor_id)::uuid END")
    op.alter_column('intake_records', 'id', server_default=sa.text('gen_random_uuid()'),
               existing_type=sa.VARCHAR(length=255),
               type_=sa.UUID(),
               existing_nullable=False, postgresql_using="CASE WHEN id ~ '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$' THEN id::uuid ELSE md5(id)::uuid END")
    op.alter_column('intake_records', 'hiring_manager_id',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.UUID(),
               existing_nullable=True, postgresql_using="CASE WHEN hiring_manager_id ~ '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$' THEN hiring_manager_id::uuid ELSE md5(hiring_manager_id)::uuid END")
    op.alter_column('intake_records', 'submitted_by',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.UUID(),
               existing_nullable=True, postgresql_using="CASE WHEN submitted_by ~ '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$' THEN submitted_by::uuid ELSE md5(submitted_by)::uuid END")
    op.alter_column('intake_skills', 'id', server_default=sa.text('gen_random_uuid()'),
               existing_type=sa.VARCHAR(length=255),
               type_=sa.UUID(),
               existing_nullable=False, postgresql_using="CASE WHEN id ~ '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$' THEN id::uuid ELSE md5(id)::uuid END")
    op.alter_column('intake_skills', 'intake_id',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.UUID(),
               existing_nullable=False, postgresql_using="CASE WHEN intake_id ~ '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$' THEN intake_id::uuid ELSE md5(intake_id)::uuid END")
    op.alter_column('intake_skills', 'skill_id',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.UUID(),
               existing_nullable=False, postgresql_using="CASE WHEN skill_id ~ '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$' THEN skill_id::uuid ELSE md5(skill_id)::uuid END")
    op.alter_column('interview_assignments', 'id', server_default=sa.text('gen_random_uuid()'),
               existing_type=sa.VARCHAR(length=255),
               type_=sa.UUID(),
               existing_nullable=False, postgresql_using="CASE WHEN id ~ '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$' THEN id::uuid ELSE md5(id)::uuid END")
    op.alter_column('interview_assignments', 'interview_id',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.UUID(),
               existing_nullable=True, postgresql_using="CASE WHEN interview_id ~ '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$' THEN interview_id::uuid ELSE md5(interview_id)::uuid END")
    op.alter_column('interview_assignments', 'interviewer_id',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.UUID(),
               existing_nullable=True, postgresql_using="CASE WHEN interviewer_id ~ '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$' THEN interviewer_id::uuid ELSE md5(interviewer_id)::uuid END")
    op.alter_column('interview_assignments', 'candidate_id',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.UUID(),
               existing_nullable=True, postgresql_using="CASE WHEN candidate_id ~ '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$' THEN candidate_id::uuid ELSE md5(candidate_id)::uuid END")
    op.alter_column('interview_feedback', 'id', server_default=sa.text('gen_random_uuid()'),
               existing_type=sa.VARCHAR(length=255),
               type_=sa.UUID(),
               existing_nullable=False, postgresql_using="CASE WHEN id ~ '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$' THEN id::uuid ELSE md5(id)::uuid END")
    op.alter_column('interview_feedback', 'interview_id',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.UUID(),
               existing_nullable=True, postgresql_using="CASE WHEN interview_id ~ '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$' THEN interview_id::uuid ELSE md5(interview_id)::uuid END")
    op.alter_column('interview_feedback', 'interviewer_id',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.UUID(),
               existing_nullable=True, postgresql_using="CASE WHEN interviewer_id ~ '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$' THEN interviewer_id::uuid ELSE md5(interviewer_id)::uuid END")
    op.alter_column('interviews', 'id', server_default=sa.text('gen_random_uuid()'),
               existing_type=sa.VARCHAR(length=255),
               type_=sa.UUID(),
               existing_nullable=False, postgresql_using="CASE WHEN id ~ '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$' THEN id::uuid ELSE md5(id)::uuid END")
    op.alter_column('interviews', 'application_id',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.UUID(),
               existing_nullable=True, postgresql_using="CASE WHEN application_id ~ '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$' THEN application_id::uuid ELSE md5(application_id)::uuid END")
    op.alter_column('interviews', 'requisition_id',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.UUID(),
               existing_nullable=True, postgresql_using="CASE WHEN requisition_id ~ '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$' THEN requisition_id::uuid ELSE md5(requisition_id)::uuid END")
    op.alter_column('interviews', 'interviewer_id',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.UUID(),
               existing_nullable=True, postgresql_using="CASE WHEN interviewer_id ~ '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$' THEN interviewer_id::uuid ELSE md5(interviewer_id)::uuid END")
    op.alter_column('interviews', 'candidate_id',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.UUID(),
               existing_nullable=True, postgresql_using="CASE WHEN candidate_id ~ '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$' THEN candidate_id::uuid ELSE md5(candidate_id)::uuid END")
    op.alter_column('interviews', 'created_by',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.UUID(),
               existing_nullable=True, postgresql_using="CASE WHEN created_by ~ '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$' THEN created_by::uuid ELSE md5(created_by)::uuid END")
    op.alter_column('leaves', 'id', server_default=sa.text('gen_random_uuid()'),
               existing_type=sa.VARCHAR(length=255),
               type_=sa.UUID(),
               existing_nullable=False, postgresql_using="CASE WHEN id ~ '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$' THEN id::uuid ELSE md5(id)::uuid END")
    op.alter_column('leaves', 'employee_id',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.UUID(),
               existing_nullable=True, postgresql_using="CASE WHEN employee_id ~ '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$' THEN employee_id::uuid ELSE md5(employee_id)::uuid END")
    op.alter_column('leaves', 'approved_by',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.UUID(),
               existing_nullable=True, postgresql_using="CASE WHEN approved_by ~ '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$' THEN approved_by::uuid ELSE md5(approved_by)::uuid END")
    op.alter_column('notification_settings', 'updated_by',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.UUID(),
               existing_nullable=True, postgresql_using="CASE WHEN updated_by ~ '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$' THEN updated_by::uuid ELSE md5(updated_by)::uuid END")
    op.create_index('idx_notification_settings_updated_by', 'notification_settings', ['updated_by'], unique=False)
    op.alter_column('offboarding_tasks', 'id', server_default=sa.text('gen_random_uuid()'),
               existing_type=sa.VARCHAR(length=255),
               type_=sa.UUID(),
               existing_nullable=False, postgresql_using="CASE WHEN id ~ '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$' THEN id::uuid ELSE md5(id)::uuid END")
    op.alter_column('offboarding_tasks', 'employee_id',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.UUID(),
               existing_nullable=False, postgresql_using="CASE WHEN employee_id ~ '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$' THEN employee_id::uuid ELSE md5(employee_id)::uuid END")
    op.alter_column('offboarding_tasks', 'assignee_id',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.UUID(),
               existing_nullable=True, postgresql_using="CASE WHEN assignee_id ~ '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$' THEN assignee_id::uuid ELSE md5(assignee_id)::uuid END")
    op.alter_column('offboarding_tasks', 'completed_by',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.UUID(),
               existing_nullable=True, postgresql_using="CASE WHEN completed_by ~ '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$' THEN completed_by::uuid ELSE md5(completed_by)::uuid END")
    op.drop_index(op.f('idx_offboarding_tasks_status'), table_name='offboarding_tasks')
    op.alter_column('onboarding_journeys', 'id', server_default=sa.text('gen_random_uuid()'),
               existing_type=sa.VARCHAR(length=255),
               type_=sa.UUID(),
               existing_nullable=False, postgresql_using="CASE WHEN id ~ '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$' THEN id::uuid ELSE md5(id)::uuid END")
    op.alter_column('onboarding_journeys', 'employee_id',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.UUID(),
               existing_nullable=False, postgresql_using="CASE WHEN employee_id ~ '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$' THEN employee_id::uuid ELSE md5(employee_id)::uuid END")
    op.alter_column('onboarding_journeys', 'template_id',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.UUID(),
               existing_nullable=False, postgresql_using="CASE WHEN template_id ~ '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$' THEN template_id::uuid ELSE md5(template_id)::uuid END")
    op.alter_column('onboarding_journeys', 'created_by',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.UUID(),
               existing_nullable=True, postgresql_using="CASE WHEN created_by ~ '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$' THEN created_by::uuid ELSE md5(created_by)::uuid END")
    op.alter_column('onboarding_task_dependencies', 'task_id',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.UUID(),
               existing_nullable=False, postgresql_using="CASE WHEN task_id ~ '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$' THEN task_id::uuid ELSE md5(task_id)::uuid END")
    op.alter_column('onboarding_task_dependencies', 'depends_on_task_id',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.UUID(),
               existing_nullable=False, postgresql_using="CASE WHEN depends_on_task_id ~ '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$' THEN depends_on_task_id::uuid ELSE md5(depends_on_task_id)::uuid END")
    op.alter_column('onboarding_task_template_dependencies', 'id', server_default=sa.text('gen_random_uuid()'),
               existing_type=sa.VARCHAR(length=255),
               type_=sa.UUID(),
               existing_nullable=False, postgresql_using="CASE WHEN id ~ '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$' THEN id::uuid ELSE md5(id)::uuid END")
    op.alter_column('onboarding_task_template_dependencies', 'task_template_id',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.UUID(),
               existing_nullable=False, postgresql_using="CASE WHEN task_template_id ~ '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$' THEN task_template_id::uuid ELSE md5(task_template_id)::uuid END")
    op.alter_column('onboarding_task_template_dependencies', 'depends_on_task_template_id',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.UUID(),
               existing_nullable=False, postgresql_using="CASE WHEN depends_on_task_template_id ~ '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$' THEN depends_on_task_template_id::uuid ELSE md5(depends_on_task_template_id)::uuid END")
    op.alter_column('onboarding_task_templates', 'id', server_default=sa.text('gen_random_uuid()'),
               existing_type=sa.VARCHAR(length=255),
               type_=sa.UUID(),
               existing_nullable=False, postgresql_using="CASE WHEN id ~ '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$' THEN id::uuid ELSE md5(id)::uuid END")
    op.alter_column('onboarding_task_templates', 'template_id',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.UUID(),
               existing_nullable=False, postgresql_using="CASE WHEN template_id ~ '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$' THEN template_id::uuid ELSE md5(template_id)::uuid END")
    op.alter_column('onboarding_task_templates', 'owner_group_id',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.UUID(),
               existing_nullable=True, postgresql_using="CASE WHEN owner_group_id ~ '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$' THEN owner_group_id::uuid ELSE md5(owner_group_id)::uuid END")
    op.alter_column('onboarding_task_templates', 'depends_on',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.UUID(),
               existing_nullable=True, postgresql_using="CASE WHEN depends_on ~ '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$' THEN depends_on::uuid ELSE md5(depends_on)::uuid END")
    op.alter_column('onboarding_tasks', 'id', server_default=sa.text('gen_random_uuid()'),
               existing_type=sa.VARCHAR(length=255),
               type_=sa.UUID(),
               existing_nullable=False, postgresql_using="CASE WHEN id ~ '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$' THEN id::uuid ELSE md5(id)::uuid END")
    op.alter_column('onboarding_tasks', 'journey_id',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.UUID(),
               existing_nullable=False, postgresql_using="CASE WHEN journey_id ~ '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$' THEN journey_id::uuid ELSE md5(journey_id)::uuid END")
    op.alter_column('onboarding_tasks', 'template_task_id',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.UUID(),
               existing_nullable=True, postgresql_using="CASE WHEN template_task_id ~ '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$' THEN template_task_id::uuid ELSE md5(template_task_id)::uuid END")
    op.alter_column('onboarding_tasks', 'owner_group_id',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.UUID(),
               existing_nullable=True, postgresql_using="CASE WHEN owner_group_id ~ '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$' THEN owner_group_id::uuid ELSE md5(owner_group_id)::uuid END")
    op.alter_column('onboarding_tasks', 'assignee_id',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.UUID(),
               existing_nullable=True, postgresql_using="CASE WHEN assignee_id ~ '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$' THEN assignee_id::uuid ELSE md5(assignee_id)::uuid END")
    op.alter_column('onboarding_tasks', 'depends_on',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.UUID(),
               existing_nullable=True, postgresql_using="CASE WHEN depends_on ~ '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$' THEN depends_on::uuid ELSE md5(depends_on)::uuid END")
    op.alter_column('onboarding_templates', 'id', server_default=sa.text('gen_random_uuid()'),
               existing_type=sa.VARCHAR(length=255),
               type_=sa.UUID(),
               existing_nullable=False, postgresql_using="CASE WHEN id ~ '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$' THEN id::uuid ELSE md5(id)::uuid END")
    op.alter_column('onboarding_templates', 'created_by',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.UUID(),
               existing_nullable=True, postgresql_using="CASE WHEN created_by ~ '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$' THEN created_by::uuid ELSE md5(created_by)::uuid END")
    op.alter_column('owner_groups', 'id', server_default=sa.text('gen_random_uuid()'),
               existing_type=sa.VARCHAR(length=255),
               type_=sa.UUID(),
               existing_nullable=False, postgresql_using="CASE WHEN id ~ '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$' THEN id::uuid ELSE md5(id)::uuid END")
    op.alter_column('owner_groups', 'manager_role_id',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.UUID(),
               existing_nullable=True, postgresql_using="CASE WHEN manager_role_id ~ '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$' THEN manager_role_id::uuid ELSE md5(manager_role_id)::uuid END")
    op.alter_column('permissions', 'id', server_default=sa.text('gen_random_uuid()'),
               existing_type=sa.VARCHAR(length=255),
               type_=sa.UUID(),
               existing_nullable=False, postgresql_using="CASE WHEN id ~ '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$' THEN id::uuid ELSE md5(id)::uuid END")
    op.alter_column('permissions', 'role_id',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.UUID(),
               existing_nullable=False, postgresql_using="CASE WHEN role_id ~ '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$' THEN role_id::uuid ELSE md5(role_id)::uuid END")
    op.alter_column('project_members', 'project_id',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.UUID(),
               existing_nullable=False, postgresql_using="CASE WHEN project_id ~ '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$' THEN project_id::uuid ELSE md5(project_id)::uuid END")
    op.alter_column('project_members', 'employee_id',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.UUID(),
               existing_nullable=False, postgresql_using="CASE WHEN employee_id ~ '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$' THEN employee_id::uuid ELSE md5(employee_id)::uuid END")
    op.alter_column('projects', 'id', server_default=sa.text('gen_random_uuid()'),
               existing_type=sa.VARCHAR(length=255),
               type_=sa.UUID(),
               existing_nullable=False, postgresql_using="CASE WHEN id ~ '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$' THEN id::uuid ELSE md5(id)::uuid END")
    op.alter_column('projects', 'project_manager_id',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.UUID(),
               existing_nullable=True, postgresql_using="CASE WHEN project_manager_id ~ '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$' THEN project_manager_id::uuid ELSE md5(project_manager_id)::uuid END")
    op.alter_column('projects', 'sales_manager_id',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.UUID(),
               existing_nullable=True, postgresql_using="CASE WHEN sales_manager_id ~ '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$' THEN sales_manager_id::uuid ELSE md5(sales_manager_id)::uuid END")
    op.alter_column('projects', 'internal_lead_id',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.UUID(),
               existing_nullable=True, postgresql_using="CASE WHEN internal_lead_id ~ '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$' THEN internal_lead_id::uuid ELSE md5(internal_lead_id)::uuid END")
    op.alter_column('projects', 'created_by',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.UUID(),
               existing_nullable=True, postgresql_using="CASE WHEN created_by ~ '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$' THEN created_by::uuid ELSE md5(created_by)::uuid END")
    op.alter_column('requisition_skills', 'requisition_id',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.UUID(),
               existing_nullable=False, postgresql_using="CASE WHEN requisition_id ~ '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$' THEN requisition_id::uuid ELSE md5(requisition_id)::uuid END")
    op.alter_column('requisition_skills', 'skill_id',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.UUID(),
               existing_nullable=False, postgresql_using="CASE WHEN skill_id ~ '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$' THEN skill_id::uuid ELSE md5(skill_id)::uuid END")
    op.alter_column('requisitions', 'id', server_default=sa.text('gen_random_uuid()'),
               existing_type=sa.VARCHAR(length=255),
               type_=sa.UUID(),
               existing_nullable=False, postgresql_using="CASE WHEN id ~ '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$' THEN id::uuid ELSE md5(id)::uuid END")
    op.alter_column('requisitions', 'intake_id',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.UUID(),
               existing_nullable=True, postgresql_using="CASE WHEN intake_id ~ '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$' THEN intake_id::uuid ELSE md5(intake_id)::uuid END")
    op.alter_column('requisitions', 'hiring_manager_id',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.UUID(),
               existing_nullable=True, postgresql_using="CASE WHEN hiring_manager_id ~ '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$' THEN hiring_manager_id::uuid ELSE md5(hiring_manager_id)::uuid END")
    op.alter_column('requisitions', 'created_by',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.UUID(),
               existing_nullable=True, postgresql_using="CASE WHEN created_by ~ '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$' THEN created_by::uuid ELSE md5(created_by)::uuid END")
    op.alter_column('role_assignment_blacklist', 'employee_id',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.UUID(),
               existing_nullable=False, postgresql_using="CASE WHEN employee_id ~ '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$' THEN employee_id::uuid ELSE md5(employee_id)::uuid END")
    op.alter_column('role_assignment_blacklist', 'role_id',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.UUID(),
               existing_nullable=False, postgresql_using="CASE WHEN role_id ~ '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$' THEN role_id::uuid ELSE md5(role_id)::uuid END")
    op.alter_column('role_assignments', 'employee_id',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.UUID(),
               existing_nullable=False, postgresql_using="CASE WHEN employee_id ~ '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$' THEN employee_id::uuid ELSE md5(employee_id)::uuid END")
    op.alter_column('role_assignments', 'role_id',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.UUID(),
               existing_nullable=False, postgresql_using="CASE WHEN role_id ~ '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$' THEN role_id::uuid ELSE md5(role_id)::uuid END")
    op.alter_column('role_assignments', 'assigned_by',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.UUID(),
               existing_nullable=True, postgresql_using="CASE WHEN assigned_by ~ '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$' THEN assigned_by::uuid ELSE md5(assigned_by)::uuid END")
    op.alter_column('role_grant_permissions', 'granting_role_id',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.UUID(),
               existing_nullable=False, postgresql_using="CASE WHEN granting_role_id ~ '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$' THEN granting_role_id::uuid ELSE md5(granting_role_id)::uuid END")
    op.alter_column('role_grant_permissions', 'assignable_role_id',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.UUID(),
               existing_nullable=False, postgresql_using="CASE WHEN assignable_role_id ~ '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$' THEN assignable_role_id::uuid ELSE md5(assignable_role_id)::uuid END")
    op.alter_column('roles', 'id', server_default=sa.text('gen_random_uuid()'),
               existing_type=sa.VARCHAR(length=255),
               type_=sa.UUID(),
               existing_nullable=False, postgresql_using="CASE WHEN id ~ '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$' THEN id::uuid ELSE md5(id)::uuid END")
    op.drop_index(op.f('idx_roles_sort_order'), table_name='roles')
    op.alter_column('skills_catalog', 'id', server_default=sa.text('gen_random_uuid()'),
               existing_type=sa.VARCHAR(length=255),
               type_=sa.UUID(),
               existing_nullable=False, postgresql_using="CASE WHEN id ~ '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$' THEN id::uuid ELSE md5(id)::uuid END")
    op.alter_column('skills_catalog', 'created_by',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.UUID(),
               existing_nullable=True, postgresql_using="CASE WHEN created_by ~ '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$' THEN created_by::uuid ELSE md5(created_by)::uuid END")
    op.drop_index(op.f('uq_skills_catalog_name_lower'), table_name='skills_catalog', postgresql_where='(deleted_at IS NULL)')
    op.alter_column('system_settings', 'updated_by',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.UUID(),
               existing_nullable=True, postgresql_using="CASE WHEN updated_by ~ '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$' THEN updated_by::uuid ELSE md5(updated_by)::uuid END")
    op.alter_column('task_attachments', 'id', server_default=sa.text('gen_random_uuid()'),
               existing_type=sa.VARCHAR(length=255),
               type_=sa.UUID(),
               existing_nullable=False, postgresql_using="CASE WHEN id ~ '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$' THEN id::uuid ELSE md5(id)::uuid END")
    op.alter_column('task_attachments', 'task_id',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.UUID(),
               existing_nullable=False, postgresql_using="CASE WHEN task_id ~ '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$' THEN task_id::uuid ELSE md5(task_id)::uuid END")
    op.alter_column('task_attachments', 'uploaded_by',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.UUID(),
               existing_nullable=True, postgresql_using="CASE WHEN uploaded_by ~ '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$' THEN uploaded_by::uuid ELSE md5(uploaded_by)::uuid END")
    op.alter_column('task_sla_events', 'id', server_default=sa.text('gen_random_uuid()'),
               existing_type=sa.VARCHAR(length=255),
               type_=sa.UUID(),
               existing_nullable=False, postgresql_using="CASE WHEN id ~ '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$' THEN id::uuid ELSE md5(id)::uuid END")
    op.alter_column('task_sla_events', 'task_id',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.UUID(),
               existing_nullable=False, postgresql_using="CASE WHEN task_id ~ '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$' THEN task_id::uuid ELSE md5(task_id)::uuid END")
    op.alter_column('timesheets', 'id', server_default=sa.text('gen_random_uuid()'),
               existing_type=sa.VARCHAR(length=255),
               type_=sa.UUID(),
               existing_nullable=False, postgresql_using="CASE WHEN id ~ '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$' THEN id::uuid ELSE md5(id)::uuid END")
    op.alter_column('timesheets', 'project_id',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.UUID(),
               existing_nullable=False, postgresql_using="CASE WHEN project_id ~ '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$' THEN project_id::uuid ELSE md5(project_id)::uuid END")
    op.alter_column('timesheets', 'employee_id',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.UUID(),
               existing_nullable=False, postgresql_using="CASE WHEN employee_id ~ '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$' THEN employee_id::uuid ELSE md5(employee_id)::uuid END")
    op.alter_column('timesheets', 'approved_by',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.UUID(),
               existing_nullable=True, postgresql_using="CASE WHEN approved_by ~ '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$' THEN approved_by::uuid ELSE md5(approved_by)::uuid END")
    
    # 3. Re-create all foreign keys
    op.create_foreign_key(None, 'employees', 'employees', ['manager_id'], ['id'])
    op.create_foreign_key(None, 'assets', 'asset_categories', ['category_id'], ['id'], onupdate='CASCADE')
    op.create_foreign_key(None, 'assets', 'employees', ['assigned_to'], ['id'])
    op.create_foreign_key(None, 'audit_events', 'employees', ['actor_id'], ['id'])
    op.create_foreign_key(None, 'candidate_activities', 'ats_candidates', ['candidate_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'candidate_activities', 'employees', ['actor_id'], ['id'])
    op.create_foreign_key(None, 'config_dropdowns', 'employees', ['created_by'], ['id'])
    op.create_foreign_key(None, 'dashboard_tasks', 'employees', ['assigned_to_id'], ['id'])
    op.create_foreign_key(None, 'employee_attachments', 'employees', ['employee_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'employee_attachments', 'employees', ['uploaded_by'], ['id'])
    op.create_foreign_key(None, 'employee_certifications', 'employees', ['employee_id'], ['id'])
    op.create_foreign_key(None, 'employee_emergency_contacts', 'employees', ['employee_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'employee_rates', 'employees', ['employee_id'], ['id'])
    op.create_foreign_key(None, 'intake_records', 'employees', ['hiring_manager_id'], ['id'])
    op.create_foreign_key(None, 'intake_records', 'employees', ['submitted_by'], ['id'])
    op.create_foreign_key(None, 'leaves', 'employees', ['employee_id'], ['id'])
    op.create_foreign_key(None, 'leaves', 'employees', ['approved_by'], ['id'])
    op.create_foreign_key(None, 'notification_settings', 'employees', ['updated_by'], ['id'])
    op.create_foreign_key(None, 'offboarding_tasks', 'employees', ['employee_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'offboarding_tasks', 'employees', ['assignee_id'], ['id'])
    op.create_foreign_key(None, 'offboarding_tasks', 'employees', ['completed_by'], ['id'])
    op.create_foreign_key(None, 'onboarding_templates', 'employees', ['created_by'], ['id'])
    op.create_foreign_key(None, 'owner_groups', 'roles', ['manager_role_id'], ['id'])
    op.create_foreign_key(None, 'permissions', 'roles', ['role_id'], ['id'])
    op.create_foreign_key(None, 'projects', 'employees', ['project_manager_id'], ['id'])
    op.create_foreign_key(None, 'projects', 'employees', ['sales_manager_id'], ['id'])
    op.create_foreign_key(None, 'projects', 'employees', ['internal_lead_id'], ['id'])
    op.create_foreign_key(None, 'projects', 'employees', ['created_by'], ['id'])
    op.create_foreign_key(None, 'role_assignment_blacklist', 'employees', ['employee_id'], ['id'])
    op.create_foreign_key(None, 'role_assignment_blacklist', 'roles', ['role_id'], ['id'])
    op.create_foreign_key(None, 'role_assignments', 'employees', ['employee_id'], ['id'])
    op.create_foreign_key(None, 'role_assignments', 'roles', ['role_id'], ['id'])
    op.create_foreign_key(None, 'role_assignments', 'employees', ['assigned_by'], ['id'])
    op.create_foreign_key(None, 'role_grant_permissions', 'roles', ['granting_role_id'], ['id'])
    op.create_foreign_key(None, 'role_grant_permissions', 'roles', ['assignable_role_id'], ['id'])
    op.create_foreign_key(None, 'skills_catalog', 'employees', ['created_by'], ['id'])
    op.create_foreign_key(None, 'system_settings', 'employees', ['updated_by'], ['id'])
    op.create_foreign_key(None, 'asset_assignment_history', 'assets', ['asset_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'asset_assignment_history', 'employees', ['assigned_to'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'asset_assignment_history', 'employees', ['assigned_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'asset_attachments', 'assets', ['asset_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'asset_attachments', 'employees', ['uploaded_by'], ['id'])
    op.create_foreign_key(None, 'employee_project_history', 'employees', ['employee_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'employee_project_history', 'projects', ['project_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'employee_project_history', 'employees', ['created_by'], ['id'])
    op.create_foreign_key(None, 'employee_skills', 'employees', ['employee_id'], ['id'])
    op.create_foreign_key(None, 'employee_skills', 'skills_catalog', ['skill_id'], ['id'])
    op.create_foreign_key(None, 'group_members', 'owner_groups', ['group_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'group_members', 'employees', ['employee_id'], ['id'])
    op.create_foreign_key(None, 'intake_approvals', 'intake_records', ['intake_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'intake_approvals', 'employees', ['approver_id'], ['id'])
    op.create_foreign_key(None, 'intake_audit', 'intake_records', ['intake_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'intake_audit', 'employees', ['actor_id'], ['id'])
    op.create_foreign_key(None, 'intake_skills', 'intake_records', ['intake_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'intake_skills', 'skills_catalog', ['skill_id'], ['id'])
    op.create_foreign_key(None, 'onboarding_journeys', 'employees', ['employee_id'], ['id'])
    op.create_foreign_key(None, 'onboarding_journeys', 'onboarding_templates', ['template_id'], ['id'])
    op.create_foreign_key(None, 'onboarding_journeys', 'employees', ['created_by'], ['id'])
    op.create_foreign_key(None, 'onboarding_task_templates', 'onboarding_templates', ['template_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'onboarding_task_templates', 'owner_groups', ['owner_group_id'], ['id'])
    op.create_foreign_key(None, 'onboarding_task_templates', 'onboarding_task_templates', ['depends_on'], ['id'])
    op.create_foreign_key(None, 'project_members', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'project_members', 'employees', ['employee_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'requisitions', 'intake_records', ['intake_id'], ['id'])
    op.create_foreign_key(None, 'requisitions', 'employees', ['hiring_manager_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'requisitions', 'employees', ['created_by'], ['id'])
    op.create_foreign_key(None, 'timesheets', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'timesheets', 'employees', ['employee_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'timesheets', 'employees', ['approved_by'], ['id'])
    op.create_foreign_key(None, 'applications', 'ats_candidates', ['candidate_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'applications', 'requisitions', ['requisition_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'applications', 'employees', ['owner_id'], ['id'])
    op.create_foreign_key(None, 'onboarding_task_template_dependencies', 'onboarding_task_templates', ['task_template_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'onboarding_task_template_dependencies', 'onboarding_task_templates', ['depends_on_task_template_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'onboarding_tasks', 'onboarding_journeys', ['journey_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'onboarding_tasks', 'onboarding_task_templates', ['template_task_id'], ['id'])
    op.create_foreign_key(None, 'onboarding_tasks', 'owner_groups', ['owner_group_id'], ['id'])
    op.create_foreign_key(None, 'onboarding_tasks', 'employees', ['assignee_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'onboarding_tasks', 'onboarding_tasks', ['depends_on'], ['id'])
    op.create_foreign_key(None, 'requisition_skills', 'requisitions', ['requisition_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'requisition_skills', 'skills_catalog', ['skill_id'], ['id'])
    op.create_foreign_key(None, 'approvals', 'onboarding_tasks', ['task_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'approvals', 'owner_groups', ['approver_group_id'], ['id'])
    op.create_foreign_key(None, 'approvals', 'employees', ['approver_user_id'], ['id'])
    op.create_foreign_key(None, 'interviews', 'applications', ['application_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'interviews', 'requisitions', ['requisition_id'], ['id'])
    op.create_foreign_key(None, 'interviews', 'employees', ['interviewer_id'], ['id'])
    op.create_foreign_key(None, 'interviews', 'ats_candidates', ['candidate_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'interviews', 'employees', ['created_by'], ['id'])
    op.create_foreign_key(None, 'onboarding_task_dependencies', 'onboarding_tasks', ['task_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'onboarding_task_dependencies', 'onboarding_tasks', ['depends_on_task_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'task_attachments', 'onboarding_tasks', ['task_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'task_attachments', 'employees', ['uploaded_by'], ['id'])
    op.create_foreign_key(None, 'task_sla_events', 'onboarding_tasks', ['task_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'interview_assignments', 'interviews', ['interview_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'interview_assignments', 'employees', ['interviewer_id'], ['id'])
    op.create_foreign_key(None, 'interview_assignments', 'ats_candidates', ['candidate_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'interview_feedback', 'interviews', ['interview_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'interview_feedback', 'employees', ['interviewer_id'], ['id'])
# ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('timesheets', 'approved_by',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('timesheets', 'employee_id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('timesheets', 'project_id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('timesheets', 'id', server_default=sa.text('gen_random_uuid()'),
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('task_sla_events', 'task_id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('task_sla_events', 'id', server_default=sa.text('gen_random_uuid()'),
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('task_attachments', 'uploaded_by',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('task_attachments', 'task_id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('task_attachments', 'id', server_default=sa.text('gen_random_uuid()'),
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('system_settings', 'updated_by',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.create_index(op.f('uq_skills_catalog_name_lower'), 'skills_catalog', [sa.literal_column('lower(name::text)')], unique=True, postgresql_where='(deleted_at IS NULL)')
    op.alter_column('skills_catalog', 'created_by',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('skills_catalog', 'id', server_default=sa.text('gen_random_uuid()'),
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.create_index(op.f('idx_roles_sort_order'), 'roles', ['sort_order'], unique=False)
    op.alter_column('roles', 'id', server_default=sa.text('gen_random_uuid()'),
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('role_grant_permissions', 'assignable_role_id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('role_grant_permissions', 'granting_role_id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('role_assignments', 'assigned_by',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('role_assignments', 'role_id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('role_assignments', 'employee_id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('role_assignment_blacklist', 'role_id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('role_assignment_blacklist', 'employee_id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('requisitions', 'created_by',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('requisitions', 'hiring_manager_id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('requisitions', 'intake_id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('requisitions', 'id', server_default=sa.text('gen_random_uuid()'),
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('requisition_skills', 'skill_id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('requisition_skills', 'requisition_id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('projects', 'created_by',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('projects', 'internal_lead_id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('projects', 'sales_manager_id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('projects', 'project_manager_id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('projects', 'id', server_default=sa.text('gen_random_uuid()'),
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('project_members', 'employee_id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('project_members', 'project_id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('permissions', 'role_id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('permissions', 'id', server_default=sa.text('gen_random_uuid()'),
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('owner_groups', 'manager_role_id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('owner_groups', 'id', server_default=sa.text('gen_random_uuid()'),
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('onboarding_templates', 'created_by',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('onboarding_templates', 'id', server_default=sa.text('gen_random_uuid()'),
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('onboarding_tasks', 'depends_on',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('onboarding_tasks', 'assignee_id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('onboarding_tasks', 'owner_group_id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('onboarding_tasks', 'template_task_id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('onboarding_tasks', 'journey_id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('onboarding_tasks', 'id', server_default=sa.text('gen_random_uuid()'),
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('onboarding_task_templates', 'depends_on',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('onboarding_task_templates', 'owner_group_id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('onboarding_task_templates', 'template_id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('onboarding_task_templates', 'id', server_default=sa.text('gen_random_uuid()'),
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('onboarding_task_template_dependencies', 'depends_on_task_template_id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('onboarding_task_template_dependencies', 'task_template_id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('onboarding_task_template_dependencies', 'id', server_default=sa.text('gen_random_uuid()'),
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('onboarding_task_dependencies', 'depends_on_task_id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('onboarding_task_dependencies', 'task_id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('onboarding_journeys', 'created_by',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('onboarding_journeys', 'template_id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('onboarding_journeys', 'employee_id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('onboarding_journeys', 'id', server_default=sa.text('gen_random_uuid()'),
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.create_index(op.f('idx_offboarding_tasks_status'), 'offboarding_tasks', ['status'], unique=False)
    op.alter_column('offboarding_tasks', 'completed_by',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('offboarding_tasks', 'assignee_id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('offboarding_tasks', 'employee_id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('offboarding_tasks', 'id', server_default=sa.text('gen_random_uuid()'),
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.drop_index('idx_notification_settings_updated_by', table_name='notification_settings')
    op.alter_column('notification_settings', 'updated_by',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('leaves', 'approved_by',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('leaves', 'employee_id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('leaves', 'id', server_default=sa.text('gen_random_uuid()'),
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('interviews', 'created_by',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('interviews', 'candidate_id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('interviews', 'interviewer_id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('interviews', 'requisition_id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('interviews', 'application_id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('interviews', 'id', server_default=sa.text('gen_random_uuid()'),
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('interview_feedback', 'interviewer_id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('interview_feedback', 'interview_id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('interview_feedback', 'id', server_default=sa.text('gen_random_uuid()'),
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('interview_assignments', 'candidate_id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('interview_assignments', 'interviewer_id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('interview_assignments', 'interview_id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('interview_assignments', 'id', server_default=sa.text('gen_random_uuid()'),
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('intake_skills', 'skill_id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('intake_skills', 'intake_id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('intake_skills', 'id', server_default=sa.text('gen_random_uuid()'),
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('intake_records', 'submitted_by',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('intake_records', 'hiring_manager_id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('intake_records', 'id', server_default=sa.text('gen_random_uuid()'),
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('intake_audit', 'actor_id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('intake_audit', 'intake_id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('intake_audit', 'id', server_default=sa.text('gen_random_uuid()'),
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('intake_approvals', 'approver_id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('intake_approvals', 'intake_id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('intake_approvals', 'id', server_default=sa.text('gen_random_uuid()'),
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('holidays', 'id', server_default=sa.text('gen_random_uuid()'),
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('group_members', 'employee_id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('group_members', 'group_id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('group_members', 'id', server_default=sa.text('gen_random_uuid()'),
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('employees', 'manager_id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('employees', 'id', server_default=sa.text('gen_random_uuid()'),
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('employee_skills', 'skill_id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('employee_skills', 'employee_id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('employee_rates', 'employee_id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('employee_rates', 'id', server_default=sa.text('gen_random_uuid()'),
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('employee_project_history', 'created_by',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('employee_project_history', 'project_id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('employee_project_history', 'employee_id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('employee_project_history', 'id', server_default=sa.text('gen_random_uuid()'),
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('employee_emergency_contacts', 'employee_id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('employee_emergency_contacts', 'id', server_default=sa.text('gen_random_uuid()'),
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('employee_certifications', 'employee_id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('employee_certifications', 'id', server_default=sa.text('gen_random_uuid()'),
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('employee_attachments', 'uploaded_by',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('employee_attachments', 'employee_id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('employee_attachments', 'id', server_default=sa.text('gen_random_uuid()'),
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('dashboard_tasks', 'assigned_to_id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('dashboard_tasks', 'source_record_id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('dashboard_tasks', 'id', server_default=sa.text('gen_random_uuid()'),
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('config_dropdowns', 'created_by',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('config_dropdowns', 'id', server_default=sa.text('gen_random_uuid()'),
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('candidate_activities', 'actor_id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('candidate_activities', 'candidate_id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('candidate_activities', 'id', server_default=sa.text('gen_random_uuid()'),
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('audit_events', 'actor_id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('audit_events', 'id', server_default=sa.text('gen_random_uuid()'),
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('ats_candidates', 'id', server_default=sa.text('gen_random_uuid()'),
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('assets', 'assigned_to',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('assets', 'category_id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.drop_constraint('uq_asset_categories_code', 'asset_categories', type_='unique')
    op.drop_index('idx_asset_categories_name', table_name='asset_categories')
    op.create_unique_constraint(op.f('asset_categories_code_key'), 'asset_categories', ['code'], postgresql_nulls_not_distinct=False)
    op.alter_column('asset_categories', 'id', server_default=sa.text('gen_random_uuid()'),
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('asset_attachments', 'uploaded_by',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('asset_attachments', 'id', server_default=sa.text('gen_random_uuid()'),
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('asset_assignment_history', 'assigned_by',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('asset_assignment_history', 'assigned_to',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('asset_assignment_history', 'id', server_default=sa.text('gen_random_uuid()'),
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('approvals', 'approver_user_id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('approvals', 'approver_group_id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('approvals', 'task_id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('approvals', 'resource_id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('approvals', 'id', server_default=sa.text('gen_random_uuid()'),
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('applications', 'owner_id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('applications', 'requisition_id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('applications', 'candidate_id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('applications', 'id', server_default=sa.text('gen_random_uuid()'),
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    # ### end Alembic commands ###
