"""update_id_asset

Revision ID: 6ac27259d060
Revises: 0015
Create Date: 2026-03-18 18:04:59.724793

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ac27259d060'
down_revision: Union[str, None] = '0023'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop foreign key constraints first
    op.drop_constraint('asset_assignment_history_asset_id_fkey', 'asset_assignment_history', type_='foreignkey')
    op.drop_constraint('asset_attachments_asset_id_fkey', 'asset_attachments', type_='foreignkey')

    # Now alter columns to UUID
    op.alter_column('assets', 'id',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.UUID(),
               existing_nullable=False,
               postgresql_using='id::uuid',
               server_default=sa.text("gen_random_uuid()"))
               
    op.alter_column('asset_assignment_history', 'asset_id',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.UUID(),
               existing_nullable=False,
               postgresql_using='asset_id::uuid')
    op.alter_column('asset_attachments', 'asset_id',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.UUID(),
               existing_nullable=False,
               postgresql_using='asset_id::uuid')

    # Re-create foreign key constraints
    op.create_foreign_key('asset_assignment_history_asset_id_fkey', 'asset_assignment_history', 'assets', ['asset_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('asset_attachments_asset_id_fkey', 'asset_attachments', 'assets', ['asset_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop foreign key constraints
    op.drop_constraint('asset_assignment_history_asset_id_fkey', 'asset_assignment_history', type_='foreignkey')
    op.drop_constraint('asset_attachments_asset_id_fkey', 'asset_attachments', type_='foreignkey')

    # Revert columns to VARCHAR
    op.alter_column('assets', 'id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False,
               postgresql_using='id::varchar',
               server_default=None)
    op.alter_column('asset_attachments', 'asset_id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False,
               postgresql_using='asset_id::varchar')
    op.alter_column('asset_assignment_history', 'asset_id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False,
               postgresql_using='asset_id::varchar')

    # Re-create foreign key constraints
    op.create_foreign_key('asset_assignment_history_asset_id_fkey', 'asset_assignment_history', 'assets', ['asset_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('asset_attachments_asset_id_fkey', 'asset_attachments', 'assets', ['asset_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
